### ISSUE TITLE
Optimize memory pool management? (mod_lua issue)

### ISSUE THREAD

**Issue by zhaozg** [xolox/lua-apr#11] opened 2011-11-27 11:06 UTC
Hello Peter.

If not in thread mode, pool works fine, but when lua-apr used in [mod_lua] for apache  http://httpd.apache.org/docs/2.3/mod/mod_lua.html,  it will failed.  
mod_lua support a few scope, please see http://httpd.apache.org/docs/2.3/mod/mod_lua.html#luascope,

You know that apache work for windows/nt is a multi-thread mode, apr will be reloaded more times, and pool that managed by to_pool() and LUA_APR_POOL_KEY keys,

I have a temp solution, that is When lua_state vm create, I will put a pool at LUA_APR_POOL_KEY  keys, that will resolve some problem, but If you makes that used sub-pool in lua apr functions, and destroy sub pool when is end, I will makes more flexible,  just like lua_apr_xlate(),

If you have time, please think about support mod_lua by some better solution.

Thanks very much.

**Comment by zhaozg** [comment] 2011-11-27 11:45
You can from here to see my changes from https://github.com/xolox/lua-apr/forkqueue

**Comment by xolox** [comment] 2011-11-27 14:54
Hi zhiguo zhao,

I don't really understand the issue yet. You said:

> If not in thread mode, pool works fine, but when lua-apr used in mod_lua for it will failed.

In what way does it fail? Does it not work correctly, does it crash, does it hang, does it generate error messages? I took a look at your fork (actually I already did so a while ago). I guess you're talking about the following changes? Below each diff I've added some notes of mine.

## [Changes to xlate.c](https://github.com/zhaozg/lua-apr/commit/c666aa55fc673c891ebddf3c750de102f23bcaa5#diff-1):

``` diff
@@ -51,7 +51,7 @@ int lua_apr_xlate(lua_State *L)
   apr_size_t todo, unused;
   char *output, *temp;

-  pool = to_pool(L);
+  apr_pool_create(&pool,to_pool(L));
   input = luaL_checklstring(L, 1, &length);
   frompage = check_codepage(L, 2);
   topage = check_codepage(L, 3);
@@ -112,11 +112,11 @@ int lua_apr_xlate(lua_State *L)
   /* I'm not sure whether any resources remain in memory after the call to
    * apr_xlate_close(). Just to make sure, we clear the global memory pool
    * now instead of waiting until the next time it's used. */
-  apr_pool_clear(pool);
+  apr_pool_destroy(pool);
   return 1;

 fail:
   free(output);
-  apr_pool_clear(pool);
+  apr_pool_destroy(pool);
   return push_status(L, status);
 }
```

So you're saying `apr.xlate()` should use a dedicated memory pool instead of using the global memory pool in the Lua state? Why though? My general rule is that when a Lua/APR C function needs a memory pool which is not associated to a userdata object, it uses the global memory pool in the Lua state. If there is a reason why the global memory pool doesn't work in mod_lua, then it seems to me like half the Lua/APR binding will be broken because the global memory pool is used everywhere.

One more thing, do these changes mean you're actually using `apr.xlate()` on Windows? Because it has never worked for me on Windows, because I couldn't get apr_iconv working correctly. Did you try the test suite, and did the xlate tests work?

## [Changes to memory_pool.c](https://github.com/zhaozg/lua-apr/commit/dfb11c3b7aaaff00f85107eed01e30ea12ad3f92#diff-2):

``` diff
@@ -22,8 +22,9 @@ static int pool_gc(lua_State *L)
   apr_pool_t **reference;

   reference = luaL_checkudata(L, 1, LUA_APR_POOL_MT);
+#if 0
   apr_pool_destroy(*reference);
-
+#endif
   return 0;
 }

@@ -55,7 +56,9 @@ apr_pool_t *to_pool(lua_State *L)
     /* Clear and return the previously created global memory pool. */
     reference = lua_touserdata(L, -1);
     memory_pool = *reference;
+#if 0
     apr_pool_clear(memory_pool);
+#endif
     lua_pop(L, 1);
   }
```

These changes mean the global memory pool will just keep growing infinitely and it will never be garbage collected, in other words you've created a memory leak. I guess this is what you were referring to with _"I have a temp solution"_.

Judging by these two changes I get the impression mod_lua is using the same Lua state (and APR memory pool) from multiple operating system threads simultaneously... I will have to go take a look at the sources for mod_lua.

 - Peter

**Comment by zhaozg** [comment] 2011-11-27 16:41
Hi,
    Sorry for my poor English.

1) Real OS thread handle more times of  HTTP request, use thread_pool loop.
2) lua_state attach to OS Thread, It has a thread global pool.
3) each HTTP Request have a pool. HTTP Handle proc should use pool in http_request_struct.
4)  lua-apr be loaded in http_handle_proc, it should attach to pool in http_request_struct.

I can't speak it clearly.  
  Please try get httpd 2.4 from its svn trunk, and run lua script with mod_lua, 
  Then Load lua-apr in lua script, do some thing that use pool, just like xlate,It will crash.

Notice, Please use thread mpm,(I use winnt_mpm), because fork mode will ignore this.

> These changes mean the global memory pool will just keep growing infinitely and it will never be garbage collected, in other >words you've created a memory leak. I guess this is what you were referring to with "I have a temp solution".
> 
> Judging by these two changes I get the impression mod_lua is using the same Lua state (and APR memory pool) from multiple >operating system threads simultaneously... I will have to go take a look at the sources for mod_lua.

I do prepare pool in lua_state, before lua_apr loaded, so I comment destroy pool in memory_pool.c

``` c
static apr_status_t ml_pool_register(lua_State *L, apr_pool_t*pool ) {
  apr_pool_t* other = NULL;
  lua_getfield(L, LUA_REGISTRYINDEX, LUA_APR_POOL_KEY);
  if (lua_isuserdata(L,-1))
    other = *(apr_pool_t**)lua_touserdata(L,-1);
  if (other != pool) {
    lua_pop(L, 1);
    lua_boxpointer(L, pool);
    lua_setfield(L, LUA_REGISTRYINDEX, LUA_APR_POOL_KEY);
    //apr_pool_userdata_setn(L,LUA_APR_POOL_KEY, ml_pool_cleanup, pool);
    apr_pool_userdata_setn(L,LUA_APR_POOL_KEY, NULL, pool);
  } else {
    lua_pop(L, 1);
  }
  return OK;
}

/* this will be run before lua_apr be loaded, so lua_apr will use r->pool, and not create a global pool */
static apr_status_t ml_lua_request(lua_State *L, request_rec *r) {
  return ml_pool_register(L, r->pool);
};
```

When request_rec destory, pool in lua_apr will be reset before to handle next request_rec 
hook ml_lua_request to mod_lua through with 

``` c
APR_OPTIONAL_HOOK(ap_lua, lua_request,  ml_lua_request, NULL,NULL,APR_HOOK_MIDDLE);
```

**Comment by zhaozg** [comment] 2011-11-27 16:45
> One more thing, do these changes mean you're actually using apr.xlate() on Windows? Because it has never worked for me >on Windows, because I couldn't get apr_iconv working correctly. Did you try the test suite, and did the xlate tests work?

I build apr2 and libiconv on windows, It works OK. And I don't like apr_iconv, It's to ugly.

**Comment by xolox** [comment] 2011-11-27 21:25
Ah okay, it's starting to make sense now, I was missing some context. If I understand you correctly you're changing mod_lua and/or Lua/APR so that they work together? So the global memory pool used by Lua/APR is now the memory pool for the request/response cycle created by Apache and/or  mod_lua? If/once this works reliably, I may include support for this with a simple command line option to the Lua/APR build process.

I tried to build Apache from SVN but trunk is broken (it cannot find apr-util because apr-util has been merged into the apr repository, but the Apache build scripts have not yet been updated). Anyway I then downloaded the following beta release from [here](http://httpd.apache.org/download.cgi#apache23):
- `httpd-2.3.15-beta.tar.bz2`
- `httpd-2.3.15-beta-deps.tar.bz2`

I built Apache with the following command line:

``` bash
./configure --with-included-apr --enable-lua --with-mpm=worker && make && sudo make install
```

Of course I also had to rebuild the Lua/APR binding against the new apr and apr-util libraries:

``` bash
# We have to change the $PATH so the Lua/APR makefile
# runs the correct `apr-1-config' and `apu-1-config' scripts
export PATH="/home/peter/httpd-2.3.15-beta/bin:$PATH"
make clean && make && sudo make install
```

I then tested a simple Lua handler which uses the Lua/APR binding:

``` lua
local apr = require 'apr'

function handle(r)
  r.content_type = "text/plain"
  r:puts("Hello World!\n")
  r:puts("MD5 of 'Lua': " .. apr.md5('Lua') .. '\n')
  r:puts("apr.xlate() output: " .. apr.xlate('foobarbaz', 'ASCII', 'UTF-8') .. "\n")
end
```

This seems to work fine. Maybe I picked the wrong MPM model? Or it breaks on Windows but works on UNIX? (I'm using Ubuntu Linux). Or I'm calling the wrong functions... Do you have an example of a Lua handler that uses the Lua/APR binding and breaks?

**Comment by zhaozg** [comment] 2011-11-28 02:36
> This seems to work fine. Maybe I picked the wrong MPM model? Or it breaks on Windows but works on UNIX? (I'm using Ubuntu Linux). Or I'm calling the wrong functions... Do you have an example of a Lua handler that uses the Lua/APR binding and breaks?

I think you build apache in linux, that use prefork mpm,   You can choice work mpm or event mpm.

**Comment by zhaozg** [comment] 2011-11-28 02:37
> Ah okay, it's starting to make sense now, I was missing some context. If I understand you correctly you're changing mod_lua and/or Lua/APR so that they work together? So the global memory pool used by Lua/APR is now the memory pool for the request/response cycle created by Apache and/or mod_lua? If/once this works reliably, I may include support for this with a simple command line option to the Lua/APR build process.

You are so clever. Happy.

**Comment by zhaozg** [comment] 2011-11-28 06:28
> @@ -419,8 +419,6 @@ int status_to_message(lua_State *L, apr_status_t status)
>    apr_strerror(status, message, count(message));
>    length = strlen(message);
> -  while (length > 0 && isspace(message[length - 1]))
> -    length--;
>   lua_pushlstring(L, message, length);
>   return 1;
>   }

This not need, because apr_strerror should handle it correctly,

**Comment by zhaozg** [comment] 2011-11-28 06:46
https://github.com/zhaozg/lua-apr/commit/2d338cf39d9bfee87b7c961bc6d816c51c62ae4c

```
diff --git a/lua-apr/src/memory_pool.c b/org/src/memory_pool.c
index cd820de..c49ffef 100644
--- a/lua-apr/src/memory_pool.c
+++ b/org/src/memory_pool.c
@@ -52,17 +52,11 @@ apr_pool_t *to_pool(lua_State *L)
     lua_setmetatable(L, -2);
     lua_setfield(L, LUA_REGISTRYINDEX, LUA_APR_POOL_KEY);
   } else {
-   reference = lua_touserdata(L, -1);
-   memory_pool = *reference;
-
-   /* __gc will be flag to clear memory pool */
-   if (luaL_getmetafield(L, -1, "__gc") && !lua_isnil(L,-1))
-   {
-       /* Clear and return the previously created global memory pool. */
-       apr_pool_clear(memory_pool);
-       lua_pop(L, 1);
-   }
-   lua_pop(L, 1);
+    /* Clear and return the previously created global memory pool. */
+    reference = lua_touserdata(L, -1);
+    memory_pool = *reference;
+    apr_pool_clear(memory_pool);
+    lua_pop(L, 1);
   }

   return memory_pool;
```

This is a solution to give other c libs to set global pool associate with L, That means pool will be managed by other c libs, not need lua-apr to handle it.
pool object metafiled __gc will be a flag, other c libs should not use this key, 
May be compare pool_gc() and pool object  __gc metafunciton is a good choice. 

Other pool related funcion(eg. pool_gc()) not need to changed.

**Comment by xolox** [comment] 2011-11-28 22:52
I don't have a lot of experience compiling Apache from source (as opposed to APR), but as I mentioned I built Apache with the following command line:

``` bash
./configure --with-included-apr --enable-lua --with-mpm=worker && make && sudo make install
```

As I understand [the documentation](http://httpd.apache.org/docs/2.0/misc/perf-tuning.html#compiletime) the `--with-mpm=worker` bit should make sure I'm running the worker MPM which is multi threaded. I also checked after building and installing that `apachectl -l` reported the worker module being loaded. Anyway maybe the bug is Windows specific or maybe I should just really stress Apache before it breaks. Let me experiment a bit more :-)

I like your idea about the `__gc` field but I'll move that check (whether to call `apr_pool_clear()` and `apr_pool_destroy()`) from Lua to C.

**Comment by xolox** [comment] 2011-11-28 22:55
My commit above introduces the function `lua_apr_pool_register(lua_State*, apr_pool_t*)`. It should do what you need. Oh wait, I should probably export that function from the DLL, since you're using Windows... (I guess you're not linking to Lua/APR statically?). Just a moment :-)

**Comment by xolox** [comment] 2011-11-28 22:59
Okay I just committed 03ad2c6957e5d6b6805ceb7a66cb374e50b7ba9a. Now Lua/APR actually exports the function `lua_apr_pool_register()` :-). I hope this helps!

**Comment by zhaozg** [comment] 2011-11-29 01:41
If lua_apr_pool_register() in lua-apr, applications must link with lua-apr, that's not good choice, app should not depends any lua extends libs, If lua_apr_pool_register imp in static in lua-apr.h, It is a good choice.

**Comment by xolox** [comment] 2011-12-01 21:59
I don't understand your point:
1. If you link statically with Lua/APR then it doesn't really matter that `lua_apr_pool_register()` is exported (you can still call the function) and of course you can redefine `LUA_APR_EXPORT` if you really don't want the function to be exported;
2. If your application really depends on Lua/APR and needs to call `lua_apr_pool_register()` then what is the problem with linking against the Lua/APR DLL?
3. If you really don't want to link against the Lua/APR DLL, there are functions to load symbols at runtime; APR supports this with the [DSO module](http://apr.apache.org/docs/apr/trunk/group__apr__dso.html).

Can you clarify what the problem is?

**Comment by zhaozg** [comment] 2011-12-02 01:10
I chose this. 3. If you really don't want to link against the Lua/APR DLL, there are functions to load symbols at runtime; APR supports this with the [DSO module](http://apr.apache.org/docs/apr/trunk/group__apr__dso.html).

The issue closed. 
Thanks very much.

**Closed as completed** 2011-12-02 01:10 UTC
