### ISSUE TITLE
lua-apr shouldn't link with the Lua shared library

### ISSUE THREAD

**Issue by asb** [xolox/lua-apr#2] opened 2010-12-22 16:51 UTC
It is unnecessary, but also incorrect to link a shared Lua library with the Lua library. Currently, both the lua-apr rockspecs and the Makefile attempt to do this. See Luiz's recent mailing list post, though more references exist. It works, but can lead to difficult to track down bugs:
http://article.gmane.org/gmane.comp.lang.lua.general/72355

**Comment by xolox** [comment] 2010-12-23 01:43
Hi Alex. I'd read Luiz' mailing list post but didn't fully comprehend the reasoning behind not linking with `-llua` for shared library modules.

I've now read a bit about [this topic on the wiki](http://lua-users.org/wiki/BuildingModules) and have come to understand that linking a shared library module with `-llua` makes it hard to use the shared library module with a statically linked Lua interpreter (which is certainly a valid use case).

I've just committed 0ae7b1c85d046173bbaef22ea4ea830eb8b50528 which removes the 'hard forward dependency' on the Lua core library from the Makefile and the latest rockspec.

Thanks for your bug report! I'm closing this issue now as the problem is fixed.

**Closed as completed by xolox** 2010-12-23 01:43 UTC
